// Region classification for every WORLD_DESTINATIONS country. Continent-based,
// not political/MENA groupings — matches how a traveler would browse (e.g.
// Egypt under Africa, not Middle East). Used to group/filter the Embassy
// Monitor admin panel across ~190 destinations.
import type { EmbassyRegion } from "./embassy-monitor-urls";

export const COUNTRY_REGION: Record<string, EmbassyRegion> = {
  "Afghanistan": "Asia",
  "Albania": "Europe",
  "Algeria": "Africa",
  "Andorra": "Europe",
  "Angola": "Africa",
  "Antigua and Barbuda": "Americas",
  "Argentina": "Americas",
  "Armenia": "Europe",
  "Australia": "Oceania",
  "Austria": "Europe",
  "Azerbaijan": "Europe",
  "Bahamas": "Americas",
  "Bahrain": "Middle East",
  "Bangladesh": "Asia",
  "Barbados": "Americas",
  "Belarus": "Europe",
  "Belgium": "Europe",
  "Belize": "Americas",
  "Benin": "Africa",
  "Bhutan": "Asia",
  "Bolivia": "Americas",
  "Bosnia and Herzegovina": "Europe",
  "Botswana": "Africa",
  "Brazil": "Americas",
  "Brunei": "Asia",
  "Bulgaria": "Europe",
  "Burkina Faso": "Africa",
  "Burundi": "Africa",
  "Cabo Verde": "Africa",
  "Cambodia": "Asia",
  "Cameroon": "Africa",
  "Canada": "Americas",
  "Central African Republic": "Africa",
  "Chad": "Africa",
  "Chile": "Americas",
  "China": "Asia",
  "Colombia": "Americas",
  "Comoros": "Africa",
  "Congo (Brazzaville)": "Africa",
  "Congo (DRC)": "Africa",
  "Costa Rica": "Americas",
  "Croatia": "Europe",
  "Cuba": "Americas",
  "Cyprus": "Europe",
  "Czech Republic": "Europe",
  "Denmark": "Europe",
  "Djibouti": "Africa",
  "Dominica": "Americas",
  "Dominican Republic": "Americas",
  "Ecuador": "Americas",
  "Egypt": "Africa",
  "El Salvador": "Americas",
  "Equatorial Guinea": "Africa",
  "Eritrea": "Africa",
  "Estonia": "Europe",
  "Eswatini": "Africa",
  "Ethiopia": "Africa",
  "Fiji": "Oceania",
  "Finland": "Europe",
  "France": "Europe",
  "Gabon": "Africa",
  "Gambia": "Africa",
  "Georgia": "Europe",
  "Germany": "Europe",
  "Ghana": "Africa",
  "Greece": "Europe",
  "Grenada": "Americas",
  "Guatemala": "Americas",
  "Guinea": "Africa",
  "Guinea-Bissau": "Africa",
  "Guyana": "Americas",
  "Haiti": "Americas",
  "Honduras": "Americas",
  "Hungary": "Europe",
  "Iceland": "Europe",
  "India": "Asia",
  "Indonesia": "Asia",
  "Iran": "Middle East",
  "Iraq": "Middle East",
  "Ireland": "Europe",
  "Israel": "Middle East",
  "Italy": "Europe",
  "Ivory Coast": "Africa",
  "Jamaica": "Americas",
  "Japan": "Asia",
  "Jordan": "Middle East",
  "Kazakhstan": "Asia",
  "Kenya": "Africa",
  "Kiribati": "Oceania",
  "Kosovo": "Europe",
  "Kuwait": "Middle East",
  "Kyrgyzstan": "Asia",
  "Laos": "Asia",
  "Latvia": "Europe",
  "Lebanon": "Middle East",
  "Lesotho": "Africa",
  "Liberia": "Africa",
  "Libya": "Africa",
  "Liechtenstein": "Europe",
  "Lithuania": "Europe",
  "Luxembourg": "Europe",
  "Madagascar": "Africa",
  "Malawi": "Africa",
  "Malaysia": "Asia",
  "Maldives": "Asia",
  "Mali": "Africa",
  "Malta": "Europe",
  "Marshall Islands": "Oceania",
  "Mauritania": "Africa",
  "Mauritius": "Africa",
  "Mexico": "Americas",
  "Micronesia": "Oceania",
  "Moldova": "Europe",
  "Monaco": "Europe",
  "Mongolia": "Asia",
  "Montenegro": "Europe",
  "Morocco": "Africa",
  "Mozambique": "Africa",
  "Myanmar": "Asia",
  "Namibia": "Africa",
  "Nauru": "Oceania",
  "Nepal": "Asia",
  "Netherlands": "Europe",
  "New Zealand": "Oceania",
  "Nicaragua": "Americas",
  "Niger": "Africa",
  "Nigeria": "Africa",
  "North Korea": "Asia",
  "North Macedonia": "Europe",
  "Norway": "Europe",
  "Oman": "Middle East",
  "Pakistan": "Asia",
  "Palau": "Oceania",
  "Palestine": "Middle East",
  "Panama": "Americas",
  "Papua New Guinea": "Oceania",
  "Paraguay": "Americas",
  "Peru": "Americas",
  "Philippines": "Asia",
  "Poland": "Europe",
  "Portugal": "Europe",
  "Qatar": "Middle East",
  "Romania": "Europe",
  "Russia": "Europe",
  "Rwanda": "Africa",
  "Saint Kitts and Nevis": "Americas",
  "Saint Lucia": "Americas",
  "Saint Vincent and the Grenadines": "Americas",
  "Samoa": "Oceania",
  "San Marino": "Europe",
  "Sao Tome and Principe": "Africa",
  "Saudi Arabia": "Middle East",
  "Senegal": "Africa",
  "Serbia": "Europe",
  "Seychelles": "Africa",
  "Sierra Leone": "Africa",
  "Singapore": "Asia",
  "Slovakia": "Europe",
  "Slovenia": "Europe",
  "Solomon Islands": "Oceania",
  "Somalia": "Africa",
  "South Africa": "Africa",
  "South Korea": "Asia",
  "South Sudan": "Africa",
  "Spain": "Europe",
  "Sri Lanka": "Asia",
  "Sudan": "Africa",
  "Suriname": "Americas",
  "Sweden": "Europe",
  "Switzerland": "Europe",
  "Syria": "Middle East",
  "Taiwan": "Asia",
  "Tajikistan": "Asia",
  "Tanzania": "Africa",
  "Thailand": "Asia",
  "Timor-Leste": "Asia",
  "Togo": "Africa",
  "Tonga": "Oceania",
  "Trinidad and Tobago": "Americas",
  "Tunisia": "Africa",
  "Turkey": "Middle East",
  "Turkmenistan": "Asia",
  "Tuvalu": "Oceania",
  "Uganda": "Africa",
  "Ukraine": "Europe",
  "United Arab Emirates": "Middle East",
  "United Kingdom": "Europe",
  "United States": "Americas",
  "Uruguay": "Americas",
  "Uzbekistan": "Asia",
  "Vanuatu": "Oceania",
  "Vatican City": "Europe",
  "Venezuela": "Americas",
  "Vietnam": "Asia",
  "Yemen": "Middle East",
  "Zambia": "Africa",
  "Zimbabwe": "Africa",
};
