// Official government URL to monitor for weekly change-detection, per
// country. Independent of visa-data.ts's checklist EMBASSY_URLS (which only
// covers the 25 destinations with a full document checklist) — this map's
// job is scoping exactly which destinations the Embassy Monitor admin panel
// and weekly cron actually watch.
export type EmbassyRegion = "Africa" | "Americas" | "Asia" | "Europe" | "Middle East" | "Oceania";

// The active monitor list. Only these destinations appear in the admin
// panel and get fetched by the weekly cron.
export const EMBASSY_MONITOR_URLS: Record<string, string> = {
    "Australia": "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing",
    "Austria": "https://www.mfa.gv.at/en/visa.html",
    "Belgium": "https://dofi.ibz.be/",
    "Canada": "https://www.canada.ca/en/immigration-refugees-citizenship/services/application.html",
    "Denmark": "https://www.nyidanmark.dk/",
    "Finland": "https://migri.fi/en/",
    "France": "https://france-visas.gouv.fr/",
    "Germany": "https://videx-national.diplo.de/",
    "Ireland": "https://www.visas.inis.gov.ie/",
    "Italy": "https://vistoperitalia.esteri.it/",
    "Japan": "https://www.mofa.go.jp/j_info/visit/visa/",
    "Netherlands": "https://www.netherlandsworldwide.nl/visas-for-the-netherlands/schengen-visa",
    "New Zealand": "https://www.immigration.govt.nz/",
    "Norway": "https://www.udi.no/en/",
    "Poland": "https://e-konsulat.gov.pl/",
    "Portugal": "https://aima.gov.pt/",
    "Singapore": "https://www.ica.gov.sg/enter-depart/entry_requirements/visa_requirements",
    "South Africa": "https://www.dha.gov.za/index.php/immigration-services/temporary-residency",
    "South Korea": "https://www.visa.go.kr/",
    "Spain": "https://www.exteriores.gob.es/Embajadas/Lagos/es/ServiciosConsulares/Paginas/Visados.aspx",
    "Sweden": "https://www.migrationsverket.se/",
    "Switzerland": "https://www.sem.admin.ch/",
    "United Arab Emirates": "https://gdrfad.gov.ae/en/visa-services",
    "United Kingdom": "https://www.gov.uk/apply-uk-visa",
    "United States": "https://ceac.state.gov/genniv/",
};

// Verified 2026-07-17 via live web research against real government/
// government-designated e-visa domains — the same rigor as the entries
// above, just not currently switched on. Requested removed from the active
// monitor on 2026-07-17 to keep the list to the original 25 destinations.
// To re-enable a country: move its line up into EMBASSY_MONITOR_URLS above.
// (13 further countries were researched and found to have no genuine
// official URL at all — e.g. Vatican City relies on Italy's Schengen regime,
// Palestine's entry is governed by Israel's system, Sudan/Eritrea/Comoros/
// Niger/Guinea-Bissau/North Korea/Tuvalu had no reachable official source —
// those aren't listed here since there was never a real URL to record.)
export const RESEARCHED_URLS_NOT_MONITORED: Record<string, string> = {
    "Afghanistan": "https://mfa.gov.af/en/page/39100",
    "Albania": "https://e-visa.al/",
    "Algeria": "https://www.mfa.gov.dz/services-for-foreigners/entry-visa-to-algeria",
    "Angola": "https://www.smevisa.gov.ao/",
    "Antigua and Barbuda": "https://immigration.gov.ag/general-services/entry-requirements/",
    "Argentina": "https://cancilleria.gob.ar/en/service/foreigners/visas",
    "Armenia": "https://evisa.mfa.am/",
    "Azerbaijan": "https://evisa.gov.az/en/",
    "Bahamas": "https://www.immigration.gov.bs/entry-requirements/",
    "Bahrain": "https://www.evisa.gov.bh/",
    "Bangladesh": "https://visa.gov.bd/",
    "Barbados": "https://www.foreign.gov.bb/visa-information/",
    "Belarus": "https://mfa.gov.by/en/visa/general/evisa/",
    "Belize": "https://immigration.gov.bz/visa/visa-requirements/",
    "Benin": "https://evisa.bj/",
    "Bhutan": "https://www.mfa.gov.bt/visa-to-enter-bhutan/",
    "Bolivia": "https://visas.cancilleria.gob.bo/",
    "Bosnia and Herzegovina": "https://www.mvp.gov.ba/en",
    "Botswana": "https://www.gov.bw/visa-applications/visa-application-visitors-visa",
    "Brazil": "https://www.gov.br/mre/pt-br/consulado-miami/information-about-visas-in-english",
    "Brunei": "https://www.immigration.gov.bn/en/",
    "Bulgaria": "https://www.mfa.bg/en/services-travel/consular-services/travel-bulgaria/visa-bulgaria",
    "Burkina Faso": "https://www.visaburkina.bf/en/home/",
    "Burundi": "https://www.migration.gov.bi/",
    "Cabo Verde": "https://portalconsular.mnec.gov.cv/en/vistos",
    "Cambodia": "https://www.evisa.gov.kh/",
    "Cameroon": "https://www.evisacam.cm/",
    "Central African Republic": "https://paris.diplomatie.gouv.cf/services/24/visa-court-sejour",
    "Chad": "https://evisa.td/",
    "Chile": "https://tramites.extranjeria.gob.cl/",
    "China": "http://cs.mfa.gov.cn/",
    "Colombia": "https://www.cancilleria.gov.co/en/procedures_services/visa/requirements",
    "Congo (Brazzaville)": "https://diplobrazza.net/etrangers-voyageant-en-republique-du-congo",
    "Congo (DRC)": "https://evisa.gouv.cd/",
    "Costa Rica": "https://migracion.go.cr/visas/",
    "Croatia": "https://mvep.gov.hr/services-for-citizens/consular-information-22802/visas-22807/22807",
    "Cuba": "https://evisacuba.cu", // low confidence: reported official portal, operator unverifiable on fetch
    "Cyprus": "https://www.gov.cy/en/information/visas/",
    "Czech Republic": "https://mzv.gov.cz/jnp/en/information_for_aliens/index.html",
    "Djibouti": "https://diplomatie.gouv.dj", // fallback: dedicated evisa.gouv.dj domain is down
    "Dominica": "https://dominica.gov.dm/services/passports-and-travel-documents-non-nationals/do-i-need-a-visa-to-enter-into-dominica",
    "Dominican Republic": "https://servicios360.mirex.gob.do/visas/",
    "Ecuador": "https://www.cancilleria.gob.ec/2020/06/15/visas-en-el-ecuador/",
    "Egypt": "https://visa2egypt.gov.eg/eVisa/HowDoIApply",
    "El Salvador": "https://rree.gob.sv/visas/",
    "Equatorial Guinea": "https://egonline.vfsevisa.com/gnq/en",
    "Estonia": "https://vm.ee/en/consular-visa-and-travel-information/visa-information",
    "Eswatini": "https://www.gov.sz/index.php/services-sp-22242747/visa",
    "Ethiopia": "https://www.evisa.gov.et/",
    "Fiji": "https://www.immigration.gov.fj/fiji-visas/",
    "Gabon": "https://evisa.dgdi.ga/",
    "Gambia": "https://gid.gov.gm/visa/",
    "Georgia": "https://www.evisa.gov.ge/",
    "Ghana": "https://evisa.immigration.gov.gh/",
    "Greece": "https://www.mfa.gr/en/services/visas-for-foreigners-traveling-to-greece/",
    "Grenada": "https://gov.gd/index.php/government/government-forms/immigration",
    "Guatemala": "https://igm.gob.gt/requisitos-de-ingreso-a-territorio-guatemalteco/",
    "Guinea": "https://www.paf.gov.gn/visa",
    "Guyana": "https://www.minfor.gov.gy/visa-information",
    "Haiti": "https://mae.gouv.ht/", // fallback: ministry homepage, no dedicated visa subpage found
    "Honduras": "https://inm.gob.hn/visas.html",
    "Hungary": "https://konzuliszolgalat.kormany.hu/en",
    "Iceland": "https://www.government.is/topics/foreign-affairs/visa-to-iceland/",
    "India": "https://indianvisaonline.gov.in/evisa/tvoa.html",
    "Indonesia": "https://evisa.imigrasi.go.id/",
    "Iran": "https://evisa.mfa.ir/en/",
    "Iraq": "https://evisa.iq/en",
    "Israel": "https://israel-entry.piba.gov.il/",
    "Ivory Coast": "https://snedai.com/e-visa/",
    "Jamaica": "https://www.pica.gov.jm/immigration/entry-visa-requirements",
    "Jordan": "https://eservices.moi.gov.jo",
    "Kazakhstan": "https://www.vmp.gov.kz/",
    "Kenya": "https://www.etakenya.go.ke/",
    "Kiribati": "https://www.mfa.gov.ki/visa/",
    "Kosovo": "https://mfa-ks.net/",
    "Kuwait": "https://kuwaitvisa.moi.gov.kw/",
    "Kyrgyzstan": "https://www.evisa.e-gov.kg/",
    "Laos": "https://laoevisa.gov.la/",
    "Latvia": "https://www.mfa.gov.lv/en/applying-visa",
    "Lebanon": "https://www.general-security.gov.lb/en",
    "Lesotho": "https://www.homeaffairs.gov.ls/immigration/",
    "Liberia": "https://visaonarrival.lis.gov.lr/",
    "Libya": "https://evisa.gov.ly/",
    "Lithuania": "https://keliauk.urm.lt/en/entry-to-lithuania/visas",
    "Luxembourg": "https://mae.gouvernement.lu/en/services-aux-citoyens/visa-immigration.html",
    "Madagascar": "https://diplomatie.gov.mg/",
    "Malawi": "https://evisa.gov.mw/",
    "Malaysia": "https://malaysiavisa.imi.gov.my/",
    "Maldives": "https://imuga.immigration.gov.mv/",
    "Mali": "https://diplomatiemdc.gouv.ml/",
    "Malta": "https://identita.gov.mt/central-visa-unit-main-page/",
    "Marshall Islands": "https://rmiimmigration.org/applications/",
    "Mauritania": "https://anrpts.gov.mr/visa/requestvisa",
    "Mauritius": "https://passport.govmu.org/passport/",
    "Mexico": "https://www.miconsulado.sre.gob.mx/visasmexicanas/",
    "Micronesia": "https://fsmembassy.fm/fsm-immigration-regulations/",
    "Moldova": "https://www.evisa.gov.md/",
    "Mongolia": "https://www.evisa.mn/",
    "Montenegro": "https://www.gov.me/en/article/visas",
    "Morocco": "https://www.acces-maroc.ma/",
    "Mozambique": "https://evisa.gov.mz/",
    "Myanmar": "https://evisa.moip.gov.mm/",
    "Namibia": "https://eservices.mhaiss.gov.na/visaonarrival",
    "Nauru": "http://naurugov.nr/about-nauru/visiting-nauru/visa-requirements.aspx",
    "Nepal": "https://nepaliport.immigration.gov.np/",
    "Nicaragua": "https://www.migob.gob.ni/migracion/",
    "Nigeria": "https://immigration.gov.ng/nigerian-visa/",
    "North Macedonia": "https://mfa.gov.mk/en-GB/konzularni-uslugi/informacii-za-vlez-vo-rsm",
    "Oman": "https://evisa.rop.gov.om/",
    "Pakistan": "https://visa.nadra.gov.pk/",
    "Palau": "https://bcbp.pw/?page_id=165",
    "Panama": "https://www.migracion.gob.pa/turistas/",
    "Papua New Guinea": "https://ica.gov.pg/",
    "Paraguay": "https://www.mre.gov.py/visasenlinea/en/home/",
    "Peru": "https://www.gob.pe/36240-solicitar-visa-de-turista-para-ingresar-al-peru",
    "Philippines": "https://evisa.gov.ph/",
    "Qatar": "https://mofa.gov.qa/en/consular-services/visas/visas",
    "Romania": "https://evisa.mae.ro/",
    "Russia": "https://evisa.kdmid.ru/",
    "Rwanda": "https://irembo.gov.rw/user/citizen/service/dgie/request_a_visa",
    "Saint Kitts and Nevis": "https://www.mofa.gov.kn/", // fallback: ministry homepage, no dedicated visa subpage found
    "Saint Lucia": "https://www.govt.lc/ministries/external-affairs-international-trade-and-civil-aviation/consular-division", // fallback: consular division page
    "Saint Vincent and the Grenadines": "https://security.gov.vc/security/index.php?option=com_content&view=article&id=708:entry-visa-application-form&catid=70&Itemid=426",
    "Samoa": "https://www.mfat.gov.ws/visas/",
    "Sao Tome and Principe": "http://www.smf.st/evisa/",
    "Saudi Arabia": "https://visa.visitsaudi.com/",
    "Senegal": "https://diplomatie.gouv.sn/index.php/demande-de-visa",
    "Serbia": "https://welcometoserbia.gov.rs/",
    "Seychelles": "https://seychelles.govtas.com/en",
    "Sierra Leone": "https://www.evisa.sl/",
    "Slovakia": "https://www.mzv.sk/en/services/information-for-foreigners/visas-for-foreigners-to-enter-sr",
    "Slovenia": "https://www.gov.si/en/registries/services/electronic-visa-application-form/",
    "Solomon Islands": "https://immigration.gov.sb/visas/",
    "Somalia": "https://etas.gov.so/",
    "South Sudan": "https://www.evisa.gov.ss/",
    "Sri Lanka": "https://eta.gov.lk/",
    "Suriname": "https://suriname.vfsevisa.com/",
    "Syria": "https://mofaex.gov.sy/en",
    "Taiwan": "https://www.boca.gov.tw/np-137-2.html",
    "Tajikistan": "https://www.evisa.tj/",
    "Tanzania": "https://eservices.immigration.go.tz/",
    "Thailand": "https://www.thaievisa.go.th/",
    "Timor-Leste": "https://www.migracao.gov.tl/html/sub0301.php",
    "Togo": "https://voyage.gouv.tg",
    "Tonga": "https://www.revenue.gov.to/immigration-and-general-services",
    "Trinidad and Tobago": "https://ttconnect.gov.tt/immigration-services-list",
    "Tunisia": "https://www.diplomatie.gov.tn/",
    "Turkey": "https://www.evisa.gov.tr/",
    "Turkmenistan": "https://www.mfa.gov.tm/en",
    "Uganda": "https://visas.immigration.go.ug/",
    "Ukraine": "https://mfa.gov.ua/en/consular-affairs/entry-and-stay-foreigners-ukraine/e-visa",
    "Uruguay": "https://www.gub.uy/ministerio-relaciones-exteriores/vivir-uruguay",
    "Uzbekistan": "https://e-visa.gov.uz/",
    "Vanuatu": "https://immigration.gov.vu/entry-and-departure-requirements-for-vanuatu/",
    "Venezuela": "https://mppre.gob.ve/detalle_turismo/4",
    "Vietnam": "https://evisa.gov.vn/",
    "Yemen": "https://mofa-ye.org/",
    "Zambia": "https://eservices.zambiaimmigration.gov.zm",
    "Zimbabwe": "https://evisa.gov.zw",
};
